name: hasm
version: '0.0.1'
synopsis: Haskell assembler EDSL
description: A DSL embedded into Haskell to generate machine code
category: Program
author: Aleksey Makarov
maintainer: aleksey.makarov@gmail.com
copyright: Aleksey Makarov
license: BSD3
homepage: https://github.com/aleksey-makarov/hasm
dependencies:
  - base >=4.6 && <5.0
tested-with: GHC == 8.10.7
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wno-redundant-constraints
extra-doc-files:
    - ChangeLog.md
    - README.md

github: aleksey-makarov/hasm

library:
  dependencies:
    - array
    - bytestring
    - exception-context-th
    - exceptions
    - lens
    - melf
    - mtl
    - singletons
    - template-haskell >= 2.16 && < 2.17
  source-dirs: src
  exposed-modules:
    - Asm.Asm
    - Asm.AArch64
    - Asm.Data
    - Asm.Ld
  other-modules:
    - Asm.Relocation

tests:
  test:
    main: Tests.hs
    source-dirs: tests
    dependencies:
      - bytestring
      - exceptions
      - filepath
      - hasm
      - melf
      - mtl
      - process
      - QuickCheck
      - tasty
      - tasty-golden
      - tasty-hunit
      - tasty-quickcheck
      - unix

executables:
  hld:
    main: hld.hs
    source-dirs: app
    ghc-options: -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bytestring
      - hasm
      - melf
      - optparse-applicative >= 0.16.1 && < 0.17
      - unix
