name: hasm
version: '0.0.1'
synopsis: Haskell assembler EDSL
description: A DSL embedded into Haskell to generate machine code
category: Program
author: Aleksey Makarov
maintainer: aleksey.makarov@gmail.com
copyright: Aleksey Makarov
license: BSD3
homepage: https://github.com/aleksey-makarov/hasm
dependencies:
  - base >=4.6 && <5.0
tested-with: GHC == 8.10.7
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wno-redundant-constraints
extra-doc-files:
    - ChangeLog.md
    - README.md

github: aleksey-makarov/hasm

library:
  dependencies:
    - template-haskell >= 2.16 && < 2.17
    - exceptions
    - singletons
    - exception-context-th
    - mtl
    - bytestring
    - melf
  source-dirs: src
  exposed-modules:
    - Asm.AsmAArch64
    - Asm.DummyLd
    - Code.HelloWorld
    - Code.ForwardLabel

tests:
  exceptions:
    main: Tests.hs
    source-dirs: tests
    dependencies:
      - bytestring
      - unix
      - filepath
      - exceptions
      - tasty
      - tasty-golden
      - tasty-hunit
      - hasm
      - melf
      - mtl
      - process

executables:
  hld:
    main: hld.hs
    source-dirs: app
    ghc-options: -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - melf
      - optparse-applicative >= 0.16.1 && < 0.17
      - githash
      - bytestring
      - hasm
